# generated by datamodel-codegen:
#   filename:  openapi.json
#   timestamp: 2023-12-07T15:36:09+00:00

from __future__ import annotations

from typing import List

from typing_extensions import TypedDict

DynamicHandleModel = TypedDict(
    'DynamicHandleModel',
    {
        '495_821': List,
    },
)
