name: Tag

on:
  push:
    tags:
      - v*
  workflow_dispatch:


jobs:
  Pypi:
    runs-on: ubuntu-latest

    container:
      image: python

    steps:
      - name: Check out git repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Fix
        run: git config --global --add safe.directory '*'

      - name: Set version
        run: |
          git fetch --all
          export TAG=$(git describe --tags)
          echo "$(FLYMYAI_PYTHON_VERSION=${TAG:1} envsubst < setup.py)" > setup.py
          echo "$(FLYMYAI_PYTHON_VERSION=${TAG:1} envsubst < pyproject.toml)" > pyproject.toml

      - name: Install dependencies
        run: pip3 install poetry && poetry config virtualenvs.create ${USE_VENV} && poetry install

      - name: Build & Publish
        run: poetry publish --username __token__ --password ${{ secrets.PYPI_API_KEY }} --build
